### ISSUE TITLE
CRAM support

### ISSUE THREAD

**Issue by talhamufeed** [iprada/Circle-Map#102]
I'm a researcher working in a low-resource setting, and I'm interested in using Circle Map for my ecDNA analysis. Due to storage limitations, we primarily work with CRAM files instead of BAM files.  Does Circle Map currently support direct input of CRAM files?

### Environment (if relevant)
- Circle Map version: [v1.1.4]
- Operating System: [Ubuntu 22.04.4 LTS]

Thank you for your time and consideration. Any insights or guidance would be greatly appreciated.

**Comment by iprada** [comment]
Hi Talha,

I am very sorry and I wish I could help on this. Supporting CRAM files is not within my future plans as I do not have time to implement new features. Supporting CRAM files will require a lot of software modifications and it is not realistic given my time.

With that being said. I am happy to try to help with suggestions
What is your compute set-up (storage, RAM, cpu power)?

best,

Iñigo Prada

**Comment by talhamufeed** [comment]
That's totally fine, I wanted to make sure before I modify my whole pipeline again for putting CRAM files into circle_map. My own personal CPU is very basic with 8GB DDR4 RAM, 256G SSD (OS runs on this) , 1TB HDD, and 4 cores i5 5th Gen. I have access to a more powerful system at my institute but currently it is busy with other analysis and it takes me days to analyze one WGS. But I'm trying to look for other solutions.
Regards,
Talha Mufeed

**Comment by iprada** [comment]
Hi, 

Makes sense to double check :) 

How many samples and at which sequencing depth are we talking about? is it standard WGS data? Circle-Seq? Human data?

best,

Iñigo

**Comment by talhamufeed** [comment]
I have 23 samples, the minimum depth is 30x. And it is human WGS standard.
Regards,
Talha Mufeed

**Comment by iprada** [comment]
I see. Sounds like you definitely need a powerful system to analyse that volume of data

**Comment by talhamufeed** [comment]
Yeah. I'm looking to do it on the cloud. Thanks alot for your prompt replies. Really appreciate it.
