### ISSUE TITLE
Circle-Map Output File

### ISSUE THREAD

**Issue by ABDULHZAU** [iprada/Circle-Map#19]
[Circle-Map Output File](https://github.com/iprada/Circle-Map/wiki/Circle-Map-output-files)
Column #5, Note #2
- If you want to filter the output by read evidence, this is a good column to apply filters to as it provides a direct evidence of the amount of reads that cross the circular DNA breakpoint. In our experiments, we got reliable results applying a filter of at least 2 split reads. However, this is very dependent on the research question you want to answer. As a rule of thumb, we recommend setting a filter of 5-10 split reads if you want to minimize the number of false positives.
-My question is, How can I apply filter on my output bed file to know the reads evidence of my circular DNA?

**Comment by iprada** [comment]
Dear Abdul,

*-My question is, How can I apply filter on my output bed file to know the reads evidence of my circular DNA?*

I am not sure I understand your question. I will assume that you want to remove the circular DNA that do not have enough split reads. You can do this in many ways. For example, using `gawk`:

`cat my_circles.bed | gawk '$5>4' > filtered_circles.bed`

This command will remove all the circular DNA not containing at least 5 split reads.

Best regards,

Iñigo

**Comment by ABDULHZAU** [comment]
Yes, you are right. You got my question, thanks. I have one more question, Can I apply a one time filter on the same way from column #5 to column #11, to get the most cleaned and good quality circular DNA in a single file?

**Comment by iprada** [comment]
Dear Abdul,

Yest, of course.

`cat my_circles.bed | gawk '$5>4' | gawk '$11<=0.2' > filtered_circles.bed`

In this way get circles with at least 5 split reads, and, covered by sequencing at 80%.

Best wishes,

Iñigo

**Comment by ABDULHZAU** [comment]
Thanks.

**Comment by ABDULHZAU** [comment]
The question is related to the above discussion, I want to know how can i find the corresponding genes of these circular DNAs? please tell me, I will be glad to know about the genes of my circular DNA.

**Comment by iprada** [comment]
Dear Abdul,

That is outside the scope of Circle-Map. I encourage you to look at Bedtools software to do that.

I am closing the issue since it is not related to Circle-Map. Please, feel free to open a new issue if you have any questions regarding Circle-Map.

Best wishes,
