### ISSUE TITLE
Circle-Map does not install properly

### ISSUE THREAD

**Issue by Ananthu3898** [iprada/Circle-Map#24]
The conda install is done, and the Circle-Map command is not accessible from bash. Throws "command not found".

**Comment by iprada** [comment]
Dear @Ananthu3898 

Thanks a lot for you using Circle-Map. You are getting a very strange error. In order to be able to help you, I will need more information. Could you please provide the command and the output of the `conda install -c bioconda circle-map` ?

Best wishes,

Inigo

**Comment by iprada** [comment]
I am closing this since I did not hear back from you.  If you (or anybody else reading this) keeps having the same problem, feel free to reopen the issue.

Best
