### ISSUE TITLE
Interpreting runtime warnings

### ISSUE THREAD

**Issue by diplockn** [iprada/Circle-Map#29]
After successfully running cirlcemap as outlined in the tutorial, I get these run time errors in the job output file and am unsure how to interpret them:

/global/home/users/diplockn/.local/lib/python3.6/site-packages/circlemap/Coverage.py:150: RuntimeWarning: invalid value encountered in ulong_scalars
  ext_array[0:(self.ilen + self.ext)])
/global/home/users/diplockn/.local/lib/python3.6/site-packages/circlemap/Coverage.py:151: RuntimeWarning: invalid value encountered in ulong_scalars
  end_coverage_ratio = np.sum(region_array[-self.ilen:]) / np.sum(ext_array[-(self.ilen + self.ext):])
/global/home/users/diplockn/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/global/home/users/diplockn/.local/lib/python3.6/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/global/home/users/diplockn/.local/lib/python3.6/site-packages/numpy/core/_methods.py:217: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/global/home/users/diplockn/.local/lib/python3.6/site-packages/numpy/core/_methods.py:186: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/global/home/users/diplockn/.local/lib/python3.6/site-packages/numpy/core/_methods.py:209: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

**Comment by iprada** [comment]
Dear @diplockn,

This warnings occur during coverage metrics calculations of the circles you have detectected. They are caused due to some division by 0 errors. For example, if Circle-Map Realigns a soft-clipped read to a genomic region where there is no coverage, you will get this warnings as some of the metrics cannot be calculated. It should be safe to ignore them

Best wishes,

Iñigo
