### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by tchrisboles** [iprada/Circle-Map#30]
Naive question. You don't need to unzip the human references to index or align with bwa, right?
Same with the samtools indexing, right?

Chris

**Comment by iprada** [comment]
Dear Chris,

I hope you are getting good results with your project :)

Regarding your question:

I have not tried myself to run bwa index & samtools with compressed files. Bwa works with compressed fastq files, but I have never tried using a compressed index.  Based on their documentation I think that they support gzip compressed files.

If I try it i will let you know.

Best wishes,

Iñigo

**Comment by tchrisboles** [comment]
I think I found the answer by trial and error last night. Bwa indexing works fine on gzip refs, but Sam indexing doesn’t- so your tutorial is probably the easiest path- that is, just work with the unzipped ref. Thanks.

Best regards, 

Chris Boles, Ph.D, Chief Scientific Officer 
Sage Science, Inc., 500 Cummings Center, Suite 2400, Beverly, MA 01915
Direct Office: +1-978-522-6284, Mobile: +1-781-856-2165
Company: +1-978-922-1832
chris.boles@sagescience.com

This e-mail may contain information that is confidential or privileged. If you are not the intended recipient, do not read, copy or distribute the e-mail or any attachments. Instead, please notify the sender and delete the e-mail and any attachments. Thank you.

**Comment by iprada** [comment]
Glad to hear!
