### ISSUE TITLE
Does circle-map work well if ecdna contains structural variation?

### ISSUE THREAD

**Issue by zhang919** [iprada/Circle-Map#32]
Dear，
I have read your paper published on Bioinformatics (https://doi.org/10.1186/s12859-019-3160-3), and thank you for your outstanding work. But I noticed that, according to some literature reports, the sequences on ecDNA may not correspond continuously to the reference genome. For example, Structurally, EGFRvIII included ecDNA dont contain several exons (1,2),  Can circle-map accurately identify this variation and display it in the output?

1. Turner, K., Deshpande, V., Beyter, D. et al. Extrachromosomal oncogene amplification drives tumour evolution and genetic heterogeneity. Nature 543, 122–125 (2017). 
2. Wu, S., Turner, K.M., Nguyen, N. et al. Circular ecDNA promotes accessible chromatin and high oncogene expression. Nature 575, 699–703 (2019).
Best.
Zhang
2020.3.21

**Comment by iprada** [comment]
Dear @zhang919,

Thanks for your nice words on our paper :)

Regarding your question:

That is a limitation on Circle-Map. Circle-Map is designed to detect the junction of the DNA circles, but it does not detect variation within the circle. Hence, Circle-Map will detect the circles in your samples (if any), but ignore the internal structure between them. Consequently, I suggest:

 - If you are interested in the internal structure use AmpliconArchitect (https://github.com/virajbdeshpande/AmpliconArchitect). I think it is a great to tool, and the developers are very nice.

 - If the internal structure of your circle is not that important for your project, I think that Circle-Map will still be very useful :)

Best,

Inigo

**Comment by zhang919** [comment]
Hi iprada,
Many thanks for your suggestions. I have successfully run circle-map and have some candidate ecDNA. It works very well and have good performance. Refer to your Suggestions, I will use AmpliconArchite to learn more about the internal structure if I need. Thank you for your work again and look forward to your continued improvement Circle-map.
Best.
Zhang

**Comment by iprada** [comment]
I am very glad to hear that you have some ecDNA candidates. And thanks a lot for your very nice words on my work. Feel free to open another issue if you have any questions.

Best,

Inigo
