### ISSUE TITLE
Is there a way to tag the split and discordant reads in bam files of each called ecDNA ?

### ISSUE THREAD

**Issue by huangyizR** [iprada/Circle-Map#36]
Hi,
Just wonder is there an easy way to mark those evidence reads so that they can be viewed through IGV ? Thanks!

**Comment by iprada** [comment]
Dear @huangyizR,

Honestly, I don't know. But I guess you could do the following:

- IGV: If your purpose is only to get a visual representation, in IGV discordants are represented in green, and soft-clipped and hard-clipped reads are represented as shorter, partial hits.

Another option would to use Gviz (https://bioconductor.org/packages/release/bioc/html/Gviz.html) to plot discordant and split reads. I personally like Gviz a lot and have used it for a bunch of papers.

I hope this helps

Best,

Inigo

**Comment by iprada** [comment]
I am closing this one. Feel free to reopen
