### ISSUE TITLE
Connection refused while downloading the raw data

### ISSUE THREAD

**Issue by gq97** [iprada/Circle-Map#38]
hello iprada, 
     I meet some problem when I was downloading the raw data, the command is as follows.
```
wget https://raw.githubusercontent.com/iprada/Circle-Map/master/tutorial/unknown_circle_reads_1.fastq
wget https://raw.githubusercontent.com/iprada/Circle-Map/master/tutorial/unknown_circle_reads_2.fastq
```
     it showed "Connection refused...", is the data available now ? Could you please help me and give me some suggestions, thank you for your attention.
Best regards.
Gu,

**Comment by gq97** [comment]
oh my god, I have found both files in tutorial/, it is sorry to disturb you.

**Comment by iprada** [comment]
You do not disturb at all :)

Feel free to open another issue if you have any questions

Best,

Iñigo
