### ISSUE TITLE
how to get ecc reads from Circle-map outputs file

### ISSUE THREAD

**Issue by panxiaoguang** [iprada/Circle-Map#39]
After running Circle-map, I can get a bed file of ECC locations. But how can I get the ECC reads? I think not all reads that in the ECC locations are ECC reads.

**Comment by iprada** [comment]
Dear @panxiaoguang 

You are right. Circle-Map Realign provides a summarized output of the eccDNA reads.BUt it does not provide direct access to the reads.

I have a beta release of that reports the output realigned in reads in BAM format, following the standard SAM format to report the realigned reads as split reads. I think that this is exactly what you are looking for. You can execute it as follows:

    Circle-Map bam2bam -i sorted_circular_dna_candidates.bam -qbam qname.bam -fasta /path/to/hg38.fa -o output.bam 

Where:

sorted_circular_dna_candidates.bam: Is the same input as `Circle-Map Realign`
 qname.bam is a query name sorted bam file

Best,

Inigo

**Comment by panxiaoguang** [comment]
Thank you very much for your reply

**Comment by panxiaoguang** [comment]
Hi, Inigo, 

after running `Circle-Map bam2bam`, I successfuly got a bam file. But when I run `samtools sort`, I got an error message "[E::bgzf_read_black] Invalid BGZF header at offset 1203765486". Have you ever encountered this error, and what are the possible reasons?
