### ISSUE TITLE
how to use Circle-map to get counts for a specific ecDNA?

### ISSUE THREAD

**Issue by shaka-emperor** [iprada/Circle-Map#42]
Dear iprada
       After using Circle-Map Realign, I can get many potential ecDNAs in .bed file. But can I get counts of a specific ecDNA by Circle-Map? or I need other software? Thanks a lot

**Comment by iprada** [comment]
Hi,

Could you elaborate a bit more?

Do you wanna get the read counts for every ecDNA in your sample? If so, do you program in python?

**Comment by shaka-emperor** [comment]
exactly, I wanna get the read counts for every ecDNA in my sample, but I don't know how to do it...

**Comment by iprada** [comment]
Do you program in python?

**Comment by shaka-emperor** [comment]
sorry... I only know it's a programming language. if it helps, I'd love to learn it

**Comment by iprada** [comment]
If you program in python, you could use pysam (https://pysam.readthedocs.io/en/latest/api.html)  to get the counts. I also thing that "bedtools coverage" does exactly what you want. If you do not know what I am talking about, I encourage you to find some bioinformatics collaborator that could help you. 

Best,

Iñigo

**Comment by shaka-emperor** [comment]
Thanks a lot~~~ these clues are really valuable ~~~

**Comment by iprada** [comment]
You are very welcome.

Sorry I cannot be more helpful. I am finishing my PhD and I am quite busy. Feel free to open a new issue if you have more questions

**Comment by shaka-emperor** [comment]
Dear iprada
  Hi, I used **bedtools coverage** to get read counts for a specific ecDNA. But how to use these reads to trace back the copy number of a specific ecDNA? 
  Besides, is it appropriate to directly use **Circle-Map realign**my_unknown_circle.bed file (split reads + discordant reads, or just split reads) to indicate ecDNA copy number? Because my understanding is that these reads contain breakpoints. For instance, if this putative ecDNA have 5 split reads, then I can say the raw data contain 5 copies of this ecDNA?

**Comment by iprada** [comment]
Hi @shaka-emperor,

This outside my scope and it heavily depends on your experimental setting. If you do not have anybody with a rigurous statistics/quantitative bioinformatics background, I encourage you to find a collaborator that could help you there.

I am sorry I cannot help more on this.

Best,

Iñigo

**Comment by shaka-emperor** [comment]
Thank you anyway, you have helped me a lot~~
