### ISSUE TITLE
Question: Tutorial step 2 skip orientation FF/RF/RR by bwa mem

### ISSUE THREAD

**Issue by shaka-emperor** [iprada/Circle-Map#48]
Dear iprada

I extracted circular DNA fragments from human somatic tissue, sequenced them, and then try to align data to the ref genome (hg38) using bwa mem. But bwa mem always skipped orientation (FF/RF/RR). Other posts also reflect such questions, but they all have the following "as there are not enough pairs by bwa mem" hints. My alignments were just "skip orientation FF; skip orientation RF; skip orientation RR". However, I can still get a whole bunch of sam file, so I just wonder whether these skips matter or not? Do they affect the circle-map analysis?

Thanks a lot

Here is the head of raw sequencing data
@A00582:345:HFVCWDSXY:2:1101:1506:1094 1:N:0:CGTACTAG+TAGATCGC
CAATTAAAACTGACTACAAAAAGAAAATATTGCATTGTAAAATAATAAAAGCATGTAAATGCTTTATAAATTTTATAGGCTATTTTCTGAGTAACTTTCCCATGATTCCCCGGTTCTGTGCTATATGGTAGCATTGCTGGAACCGGAAGT
+
:F,FFFFFFFFFFF,F:F:FFFF:FF:FF:FF,,FFFFFF:,FFFFFF:F::FFFF:FFFFFF:FFF:FF,FFFFFFF:FFFFF:F:FFFFF,FFFFF,:FFFFFFF,,FF:FFF:FF:,,,FFFFFFFFF,:FF,FF:,:F:,FF::,F
@A00582:345:HFVCWDSXY:2:1101:3152:1094 1:N:0:CGTACTAG+TAGATCGC
GTGAAGAGCTGCATTAGGAATCTTAAGGTGGAGGTTGGGGTAGGTGGCTTGAGCTGTCTCTTATACACATCTCCCAGCCCACGAGACCGTACTAGATCGCGTATGCCGTCGTCTTCGTGCACAGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
FFF:FF,FFFFFFFFFFFFFFFF:FFFF::FFF,:FFF,F,FFFFFFFFFFFFFFF:FFFF:FFFFFFFFF:FFFFFFFFFFFFFFF:FF,FFFFFFF,FFFFFF,FFFF,:,,,,,:,,:,,,,:FFFFFFFFFFFFFFFFFFFFFFFF
@A00582:345:HFVCWDSXY:2:1101:4562:1094 1:N:0:CGTACTAG+TAGATCGC
GGATTAGAGGCAGTGATCTACACATTCATTAAAGAAGCATTGAAGTAAATTATGAATCCCGTGATGCATATTGAATCTGTCTCTTATACACATCTCCGAGCCCACGAGACCGTACTAGATCTCGTAAGCCGTCTTCTGCGTGAAAAGGGG

And here is the head of running status
https://ibb.co/4TgrMSz

**Comment by iprada** [comment]
Hi @shaka-emperor,

That means that bwa is skipping the FF,RF and RR reads when to calculate the insert size distribution.  Those are common warnings. I do not think you have anything to worry about. 

Best,

Iñigo

**Comment by shaka-emperor** [comment]
So when analyzing structural variations (like ecDNA), these FF/RF/RR reads are included?  (They are neglected only in insertion size distribution?)

**Comment by iprada** [comment]
As far as I am aware, yes. BWA neglects them for the insert size distribution calculations, but flags them correctly when they have non-concordant orientations.

Best,

Iñigo

**Comment by shaka-emperor** [comment]
Thank you very much~~

**Comment by iprada** [comment]
Wonderful. Feel free to open a new issue if you have more question, and have a happy circle hunt!
