### ISSUE TITLE
ImportError: Bio.Alphabet has been removed from Biopython.

### ISSUE THREAD

**Issue by shaka-emperor** [iprada/Circle-Map#49]
Dear iprada
      sorry to bother you again,  today I updated conda and circle-map, but latest version of circle-map report an error saying that

Circle-Map ReadExtractor -i qname_unknown_circle.bam -o circular_read_candidates.bam

_**Traceback (most recent call last):
  File "/home/yjy/anaconda3/bin/Circle-Map", line 6, in <module>
    from circlemap.circle_map import main
  File "/home/yjy/anaconda3/lib/python3.8/site-packages/circlemap/circle_map.py", line 39, in <module>
    from circlemap.simulations import sim_ecc_reads
  File "/home/yjy/anaconda3/lib/python3.8/site-packages/circlemap/simulations.py", line 30, in <module>
    from Bio.Alphabet import generic_dna
  File "/home/yjy/anaconda3/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
./circle-map-half.sh: line 7: samtools: command not found
./circle-map-half.sh: line 8: samtools: command not found
./circle-map-half.sh: line 9: samtools: command not found
Traceback (most recent call last):
  File "/home/yjy/anaconda3/bin/Circle-Map", line 6, in <module>
    from circlemap.circle_map import main
  File "/home/yjy/anaconda3/lib/python3.8/site-packages/circlemap/circle_map.py", line 39, in <module>
    from circlemap.simulations import sim_ecc_reads
  File "/home/yjy/anaconda3/lib/python3.8/site-packages/circlemap/simulations.py", line 30, in <module>
    from Bio.Alphabet import generic_dna
  File "/home/yjy/anaconda3/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.**_

  I have seen other issue indicated that installing biopyhon=1.77 may be helpful, but it didn't work for me. So I am confused again (sigh)

**Comment by iprada** [comment]
Dear @shaka-emperor,

What is your biopython version? 

Best,

Inigo

**Comment by shaka-emperor** [comment]
why does it fail? I don't understand..

$ python
Python 3.8.3 (default, Jul  2 2020, 16:21:59) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Bio
>>> print Bio._version_
  File "<stdin>", line 1
    print Bio._version_
          ^

**Comment by shaka-emperor** [comment]
import Bio
print Bio._version_

**Comment by shaka-emperor** [comment]
print Bio._version_

**Comment by iprada** [comment]
try the following;

    print(Bio.__version__)

**Comment by shaka-emperor** [comment]
wow, there have two underlines for each, and the version is 1.78 (lol)

**Comment by shaka-emperor** [comment]
haha, I fixed it, thanks a lot~

**Comment by iprada** [comment]
No worries :) Feel free to open more issues if you have any questions!

**Comment by ZHONGHONGXIN** [comment]
Hi, l meet the same error.
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
and my python version is 3.8.3, biopython version is 1.78, could you please tell me some advice?
