### ISSUE TITLE
Command help

### ISSUE THREAD

**Issue by gq97** [iprada/Circle-Map#53]
Hello iprada,
I have tried CIRCexplorer2 to detect eccDNA as mentioned in your paper, but I got few eccDNA output. I guess I misused the command of CIRCexplorer2. Could you please tell me the detail command to run CIRCexplorer2 to detect eccDNA,  if the input is 2 fastq files or the sam file.
Best wishes,
Gu

**Comment by iprada** [comment]
Dear @gq97,

Sorry for the late reply. I just came by from vacation.

The command should be:

    CIRCexplorer2 parse -t BWA -b {output.circexplorer_file} {input.filter_bam}

Where:
- "{output.circexplorer_file}" Is the name of the output file.
-  "{input.filter_bam}" it is a bam file.

I encourage you to check CIRCexplorer2 docs (https://circexplorer2.readthedocs.io/en/latest/). They are very good.

Best,

Inigo

**Comment by gq97** [comment]
Thank you very much. I found that help.
