### ISSUE TITLE
combining samples before Circle-Map analysis

### ISSUE THREAD

**Issue by hartlama** [iprada/Circle-Map#60]
Hello,

I am following the Realign tutorial and am hoping to combine 3 samples in my analysis. My question is: at which step should I merge the .sam/.bam files? Right before I use the Circle-Map ReadExtractor command??

Thank you

**Comment by iprada** [comment]
Hi,

Could you elaborate a bit more on what are the "3 samples"?

Are they technical replicates?

best,

Inigo

**Comment by hartlama** [comment]
Hi Inigo,
They are technical replicates, yes. Sorry for the vagueness.
Thank you

**Comment by iprada** [comment]
No worries :)

I think that the safest way would be to concatenate the raw aligned BAM files using somenthing like samtools merge

best,
Inigo

**Comment by hartlama** [comment]
Okay, thank you!

**Comment by iprada** [comment]
You are very welcome.

Happy circle hunting :)
