### ISSUE TITLE
Criteria for filtering

### ISSUE THREAD

**Issue by njaupan** [iprada/Circle-Map#67]
Hello,
May I ask what criteria do you use to filter the output of Circle-Map Realign?
Circle-Map has reported 7102 circles in my plant genome and it seems to contain a lot of false positives. Should I maily filter by  split reads number that at least 1 discordant reads and 5 split reads in the site?

cat Circle-Map.output |awk '$4>=1 & $5 >=5' 

Best wishes,
Panpan

**Comment by iprada** [comment]
Hi, 

Sorry for the late reply. I think filtering should be done in a project specific manner. See section "Genome-wide circular DNA detection in young and aged cells" in the following paper (https://academic.oup.com/nar/article/48/14/7883/5866106?login=true#210155825) to see how we did it sometimes.

**Comment by njaupan** [comment]
many thanks!
