### ISSUE TITLE
Could not retrieve index file for examples

### ISSUE THREAD

**Issue by ShixiangWang** [iprada/Circle-Map#68]
Hi, 

I am following the https://github.com/iprada/Circle-Map/wiki/Tutorial:-Identification-of-circular-DNA-using-Circle-Map-Realign to learn how to use this tool, but it failed in the 3rd step.

```bash
$ Circle-Map ReadExtractor -i qname_unknown_circle.bam -o circular_read_candidates.bam
[E::idx_find_and_load] Could not retrieve index file for '/public/home/zhaoqi/test/Circle-Map/tutorial/qname_unknown_circle.bam'
Extracting circular structural variants
finished extracting reads. Elapsed time: 0.00025257269541422524 mins
Thanks for using Circle-Map
```

Any suggestions?

**Comment by ShixiangWang** [comment]
The steps afterwards works.

**Comment by eallen-bbi** [comment]
Hello - I get the same error with the demo data, but the resulting BAM file has no alignment records.

**Comment by ShixiangWang** [comment]
Just ignore this message

**Comment by ShixiangWang** [comment]
Go through all steps and see how it works.

**Comment by eallen-bbi** [comment]
Thanks for reply.  I determined that the initial bam has alignments, but they all have mapq = 0, and thus are filtered out.  So that's the problem.

**Comment by eallen-bbi** [comment]
I've isolated what's going on.  I will log a new issue for that.
