### ISSUE TITLE
How to assign independent mapping quality scores to split read alignments for bam files?

### ISSUE THREAD

**Issue by ShixiangWang** [iprada/Circle-Map#69]
Hi, 

I want to apply the tool to some TCGA samples, which already have the bam files available. I see the second step is using BWA with `-q` option. I think the preprocessing of TCGA sample did not use this option. So how can I do this in samtools or similar tools?

![image](https://user-images.githubusercontent.com/25057508/126923860-07c4beed-e702-4b30-9e8f-f786115fda11.png)

Best,

Shixiang

**Comment by panxiaoguang** [comment]
I think you can use bazam and bwa to realign you bam file.

**Comment by ShixiangWang** [comment]
Thanks :)
