### ISSUE TITLE
Question regarding the "Circle score"

### ISSUE THREAD

**Issue by ko0000** [iprada/Circle-Map#73]
Hi, I'm new to this field and trying to identify/verify the true eccDNA from my WGS data. Could you explain the "circle score" a little more? How it was calculated ? (equation?)

In the reference paper, you mentioned:
"a circular DNA mapping score, calculated by multiplying the length of the split read by its mapping probability, and summing over all the scores for the split reads supporting a circle" 
,which I was not fully understand. 

Many thanks!

Ko

**Comment by iprada** [comment]
The whole idea is to arrive to an additive scoring scheme that takes into account the amount of reads (more better), the length of the read (ore better) and the mapping probability (higher better)

**Comment by ko0000** [comment]
> The whole idea is to arrive to an additive scoring scheme that takes into account the amount of reads (more better), the length of the read (ore better) and the mapping probability (higher better)

Thank you! So you simply add the numbers together? Have you set a specific weight to any of the parameters in your equation? or given every parameter an equal weight when calculating  "circle score"? 

(e.g., If the "length of the reads" is more important than the other parameter when indicating eccDNA, you give the "length of the reads" more weight than the other parameters when adding the score together to get the circle score)

Best, 

Ko

**Comment by iprada** [comment]
Sorry for the late reply. In a very hacky manner. So that it was helpful for some collaborators. I have therefore not explore anything about it.

best,

Inigo
