### ISSUE TITLE
Problems with 'Split reads' and' Discordants reads'  

### ISSUE THREAD

**Issue by Leo152** [iprada/Circle-Map#74]
Hi,
I would like to ask: there are only the number of 'Split reads' and' Discormekong reads' in the output result. How do I get information about these reads?  

Thinks

**Comment by iprada** [comment]
Can you elaborate more? I do not understand the question

**Comment by Leo152** [comment]
Circle-map only gives the number of reads in the output file. Can I get the read name from Circle-map?
