### ISSUE TITLE
The output files of Circle Map Repeats

### ISSUE THREAD

**Issue by shaka-emperor** [iprada/Circle-Map#77]
Hi, the output files of Circle Map Repeats have 10 columns, while the Circle Map Realign has 11. So, which column is missing?  Standard deviation? And, does it appropriate to apply Circle Map Repeats to Homo Sapien?
Thanks a lot~

**Comment by nemitheasura** [comment]
Same question here. Could you provide the column headers?

**Comment by iprada** [comment]
Hi both,

Thanks for pointing it out. I should update the docs.

Using the output of the tutorial as an example:

    chrXII  451417  468889  3018    .       19.510931776556774      5.131087870100604       1.0     0.9081364829396326      0.002461080586080586

From left to right:
- col1,2,3: genome coordinates
- col4: Number of "repeat reads" supporting the circle
- col5: No split reads in the repeats pipeline. Therefore always a dot
- col6-10: coverage metrics, as described in columns 7-11 of Circle-Map Repeats output.

The column missing is the circle score, as it doesn't make that much sense to calculate it on this case.


best,

Inigo
